import { AppProps} from 'next/dist/shared/lib/router/router';
import '../styles/globals.css';
import Head from "next/head";
import React from 'react';

function MyApp({ Component, pageProps } : AppProps): JSX.Element {
  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/public/favicon.ico" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Sans+Mono:wght@300;400;500;600;700&display=swap" />
    </Head>
    <Component {...pageProps} />
  </>;
}

export default MyApp;
